version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fadiladarahma/todo-fullstack:latest
    container_name: todo_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: my_database_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
